general {
    fail_timeout = 0
}

background {
    monitor =
    crossfade_time = 1
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color=rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false

    position = 0, 0
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 1.0)
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    position = 0, 35%
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, 0.8)
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    position = 0, 25%
    halign = center
    valign = center
}

label {
    monitor =
    text = 󰐥ㅤ
    color = rgba(255, 255, 255, 0.85)
    font_size = 28
    font_family = JetBrainsMono Nerd Font
    onclick = systemctl poweroff
    position = -2.5%, 0px
    halign = right
    valign = top
}

label {
    monitor =
    text = 󰜉ㅤ
    color = rgba(255, 255, 255, 0.85)
    font_size = 28
    font_family = JetBrainsMono Nerd Font
    onclick = systemctl reboot
    position = -0%, 0px
    halign = right
    valign = top
}
