hl.on("hyprland.start", function()
    hl.exec_cmd("foot --server")
    hl.exec_cmd("noctalia")
    hl.exec_cmd("kclockd")
    hl.exec_cmd("systemctl --user restart openrgb.service")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
